<div class="container">
    <h1 class="text-center">Meet Our Developers</h1>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <img src="../../../../public/assets/images/ester.jpeg" class="card-img-top" alt="Ester Santos Oliveira" title="Ester">
                <div class="card-body">
                    <h5 class="card-title">Ester Santos Oliveira</h5>
                    <!-- <p class="card-text"></p> -->
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <img src="../../../../public/assets/images/Lorena.jpg" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">Lorena</h5>
                    <!-- <p class="card-text"></p> -->
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>